In [7]:
import numpy as np
new_array=np.array([[1,2,3],[4,5,6]])
num_list =new_array.tolist()
print(num_list)

[[1, 2, 3], [4, 5, 6]]


In [9]:
import numpy as np
  
n_array = np.array([[1, 2, 3 , 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [12, 14, 15, 16]])
  
print("Numpy Matrix is:")
print(n_array)
  
trace = np.trace(n_array)
  
  
print("\nTrace of given matrix:")
print(trace)

Numpy Matrix is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [12 14 15 16]]

Trace of given 4X4 matrix:
34


In [19]:
import numpy as np
array = np.array([[1,2],[3,5]])
print("Original array: ")
print(array)
x= int(input("give a number"))
print("Values bigger than ", x , "is ", array[array>x])


Original array: 
[[1 2]
 [3 5]]
give a number2
Values bigger than  2 is  [3 5]


In [21]:
import numpy as np
A = np.array([[1,2],[3,5]])
B = np.array([[4,6],[10,5]])
print(np.add(A,B))

[[ 5  8]
 [13 10]]
